# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormdb', '0010_auto_20170330_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='roomName',
        ),
    ]
