# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormdb', '0011_remove_dorm_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='roomName',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
