# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormdb', '0012_dorm_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='relay',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
